// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import * as path from 'path';
import { defineConfig } from 'prisma/config';

const nodeEnv = process.env['NODE_ENV']?.trim() || 'development';

// Mirror the Nest app's env resolution so Prisma CLI targets the expected DB per NODE_ENV.
dotenv.config({
  path: path.resolve(__dirname, `.env.${nodeEnv}.local`),
  override: true,
});
dotenv.config({
  path: path.resolve(__dirname, `.env.${nodeEnv}`),
  override: true,
});
dotenv.config({ path: path.resolve(__dirname, '.env') });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'] ?? '',
  },
});
