import { AssistantPolicyService } from './assistant-policy.service';

describe('AssistantPolicyService', () => {
  const service = new AssistantPolicyService();

  it('derives executable tools from foundation and user settings', () => {
    const policy = service.evaluate(
      {
        phase: 'foundation',
        chatModelConfigured: true,
        interactiveChatReady: true,
        langGraphReady: true,
        ragEnabled: false,
        graphNodeNames: ['prepare_context', 'respond'],
        toolNames: [
          'get_today_records',
          'get_records_by_date',
          'get_records_by_range',
          'get_today_summary_by_date',
          'get_report_summary_by_range',
          'get_recent_today_summaries',
          'get_recent_report_summaries',
          'get_user_profile',
          'get_user_settings',
          'get_current_medicines',
          'get_sleep_summary_by_range',
          'propose_create_daily_record',
          'propose_update_daily_record',
          'propose_delete_daily_record',
          'propose_update_user_settings',
        ],
        implementedToolNames: [
          'get_today_records',
          'get_records_by_date',
          'get_records_by_range',
          'get_today_summary_by_date',
          'get_report_summary_by_range',
          'get_recent_today_summaries',
          'get_recent_report_summaries',
          'get_user_profile',
          'get_user_settings',
          'get_current_medicines',
          'get_sleep_summary_by_range',
          'propose_create_daily_record',
          'propose_update_daily_record',
          'propose_delete_daily_record',
          'propose_update_user_settings',
        ],
        contextSources: [
          'health_profile',
          'daily_records',
          'sleep_records',
          'current_medicines',
        ],
      },
      {
        aiSummariesEnabled: true,
        dataSharingConsent: false,
        assistantEnabled: true,
        assistantMemoryEnabled: false,
        assistantContext: {
          healthProfile: true,
          dailyRecords: false,
          sleepRecords: true,
          currentMedicines: true,
        },
        updatedAt: '2026-06-17T12:00:00.000Z',
      },
    );

    expect(policy.interactiveChatReady).toBe(true);
    expect(policy.enabledContextSources).toEqual([
      'health_profile',
      'sleep_records',
      'current_medicines',
    ]);
    expect(policy.contextPermittedToolNames).toEqual([
      'get_today_summary_by_date',
      'get_report_summary_by_range',
      'get_recent_today_summaries',
      'get_recent_report_summaries',
      'get_user_profile',
      'get_user_settings',
      'get_current_medicines',
      'get_sleep_summary_by_range',
      'propose_create_daily_record',
      'propose_update_user_settings',
    ]);
    expect(policy.executableToolNames).toEqual([
      'get_today_summary_by_date',
      'get_report_summary_by_range',
      'get_recent_today_summaries',
      'get_recent_report_summaries',
      'get_user_profile',
      'get_user_settings',
      'get_current_medicines',
      'get_sleep_summary_by_range',
      'propose_create_daily_record',
      'propose_update_user_settings',
    ]);
    expect(policy.toolCapabilities).toEqual([
      {
        name: 'get_today_records',
        requiredContextSources: ['daily_records'],
        permittedByUser: false,
        implemented: true,
        enabled: false,
        disabledReason: 'context_disabled',
      },
      {
        name: 'get_records_by_date',
        requiredContextSources: ['daily_records'],
        permittedByUser: false,
        implemented: true,
        enabled: false,
        disabledReason: 'context_disabled',
      },
      {
        name: 'get_records_by_range',
        requiredContextSources: ['daily_records'],
        permittedByUser: false,
        implemented: true,
        enabled: false,
        disabledReason: 'context_disabled',
      },
      {
        name: 'get_today_summary_by_date',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_report_summary_by_range',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_recent_today_summaries',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_recent_report_summaries',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_user_profile',
        requiredContextSources: ['health_profile'],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_user_settings',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_current_medicines',
        requiredContextSources: ['current_medicines'],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'get_sleep_summary_by_range',
        requiredContextSources: ['sleep_records'],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'propose_create_daily_record',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
      {
        name: 'propose_update_daily_record',
        requiredContextSources: ['daily_records'],
        permittedByUser: false,
        implemented: true,
        enabled: false,
        disabledReason: 'context_disabled',
      },
      {
        name: 'propose_delete_daily_record',
        requiredContextSources: ['daily_records'],
        permittedByUser: false,
        implemented: true,
        enabled: false,
        disabledReason: 'context_disabled',
      },
      {
        name: 'propose_update_user_settings',
        requiredContextSources: [],
        permittedByUser: true,
        implemented: true,
        enabled: true,
        disabledReason: null,
      },
    ]);
  });
});
