import type { AdminResourceConfig } from '../types/admin.types';

export const ADMIN_ROOT_PATH = '/admin';
export const SCHEMA_DIR = 'prisma';
export const SCHEMA_MAIN_FILE = 'schema.prisma';
export const ADMIN_EMAIL_KEY = 'ADMIN_EMAIL';
export const ADMIN_PASSWORD_KEY = 'ADMIN_PASSWORD';
export const ADMIN_COOKIE_SECRET_KEY = 'ADMIN_COOKIE_SECRET';
export const NODE_ENV_KEY = 'NODE_ENV';

export const DEFAULT_SENSITIVE_FIELDS = new Set([
  'password',
  'refreshTokenHash',
  'pushToken',
  'rawProfile',
]);

export const AUTO_TITLE_PROPERTY_CANDIDATES = [
  'name',
  'email',
  'contentZh',
  'title',
  'nickname',
  'id',
];

/**
 * Manual overrides for well-known models. Any model not listed here is still
 * discovered automatically from the Prisma DMMF and gets sensible defaults.
 */
export const coreResourceOverrides: Record<
  string,
  Partial<AdminResourceConfig>
> = {
  User: {
    navigation: 'Users',
    listProperties: ['id', 'email', 'nickname', 'status', 'createdAt'],
    showProperties: [
      'id',
      'email',
      'nickname',
      'avatar',
      'status',
      'emailVerifiedAt',
      'lastLoginAt',
      'deletedAt',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['email', 'nickname', 'status', 'createdAt'],
    titleProperty: 'email',
    sort: { sortBy: 'createdAt', direction: 'desc' },
  },
  Account: {
    navigation: 'Authentication',
    hiddenProperties: ['password'],
    titleProperty: 'accountId',
  },
  UserProfile: {
    navigation: 'Users',
    listProperties: ['userId', 'sexAtBirth', 'heightCm', 'bloodType', 'locale'],
    showProperties: [
      'userId',
      'birthDate',
      'sexAtBirth',
      'heightCm',
      'bloodType',
      'locale',
      'timezone',
      'unitSystem',
      'onboardingCompletedAt',
      'extras',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['userId', 'sexAtBirth', 'bloodType', 'locale'],
    titleProperty: 'userId',
  },
  DrugbankDrug: {
    navigation: 'Medicine Knowledge',
    listProperties: ['drugbankId', 'name', 'drugType', 'casNumber'],
    showProperties: [
      'drugbankId',
      'name',
      'drugType',
      'casNumber',
      'unii',
      'state',
      'groups',
      'indication',
      'mechanismOfAction',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['drugbankId', 'name', 'drugType', 'casNumber'],
    titleProperty: 'name',
  },
  CnMedicineProduct: {
    navigation: 'Medicine Knowledge',
    listProperties: [
      'id',
      'name',
      'manufacturer',
      'approvalNumber',
      'drugType',
      'mainCategory',
    ],
    showProperties: [
      'id',
      'sourceName',
      'name',
      'manufacturer',
      'approvalNumber',
      'drugType',
      'mainCategory',
      'subcategory',
      'brandName',
      'ingredients',
      'indications',
      'dosage',
      'sourceUrl',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: [
      'name',
      'manufacturer',
      'approvalNumber',
      'drugType',
      'mainCategory',
    ],
    titleProperty: 'name',
  },
  UserDailyRecord: {
    navigation: 'Health Records',
    listProperties: ['id', 'userId', 'kind', 'occurredAt', 'title', 'value'],
    showProperties: [
      'id',
      'userId',
      'kind',
      'occurredAt',
      'occurredTime',
      'title',
      'value',
      'unit',
      'note',
      'payload',
      'source',
      'deletedAt',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['userId', 'kind', 'occurredAt', 'deletedAt'],
    sort: { sortBy: 'occurredAt', direction: 'desc' },
  },
  UserDailyRecordAttachment: {
    navigation: 'Health Records',
    listProperties: [
      'id',
      'userId',
      'recordId',
      'kind',
      'provider',
      'objectKey',
    ],
    showProperties: [
      'id',
      'userId',
      'recordId',
      'kind',
      'objectKey',
      'bucket',
      'provider',
      'fileName',
      'contentType',
      'sizeBytes',
      'width',
      'height',
      'publicUrl',
      'createdAt',
    ],
    filterProperties: ['userId', 'recordId', 'kind', 'provider'],
    sort: { sortBy: 'createdAt', direction: 'desc' },
  },
  UserMedicineDoseLog: {
    navigation: 'Health Records',
    listProperties: [
      'id',
      'userId',
      'status',
      'scheduledFor',
      'currentMedicineId',
    ],
    showProperties: [
      'id',
      'userId',
      'currentMedicineId',
      'status',
      'scheduledFor',
      'takenAt',
      'doseText',
      'note',
      'source',
      'deletedAt',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['userId', 'status', 'scheduledFor', 'currentMedicineId'],
    sort: { sortBy: 'scheduledFor', direction: 'desc' },
  },
  MedicineSafetyTip: {
    navigation: 'Medicine Knowledge',
    listProperties: [
      'id',
      'contentZh',
      'contentEn',
      'category',
      'sortOrder',
      'isActive',
    ],
    showProperties: [
      'id',
      'contentZh',
      'contentEn',
      'category',
      'sortOrder',
      'isActive',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['category', 'isActive'],
    titleProperty: 'contentZh',
    sort: { sortBy: 'sortOrder', direction: 'asc' },
    readOnly: false,
    properties: {
      category: {
        availableValues: [
          { value: 'alcohol', label: 'alcohol' },
          { value: 'caffeine', label: 'caffeine' },
          { value: 'timing', label: 'timing' },
          { value: 'storage', label: 'storage' },
          { value: 'food', label: 'food' },
          { value: 'pregnancy', label: 'pregnancy' },
          { value: 'allergy', label: 'allergy' },
          { value: 'driving', label: 'driving' },
        ],
      },
    },
  },
  LegalDocument: {
    navigation: 'Legal & Compliance',
    listProperties: ['id', 'docType', 'titleZh', 'titleEn', 'isActive'],
    showProperties: [
      'id',
      'docType',
      'titleZh',
      'titleEn',
      'contentZh',
      'contentEn',
      'isActive',
      'createdAt',
      'updatedAt',
    ],
    filterProperties: ['docType', 'isActive'],
    titleProperty: 'docType',
    sort: { sortBy: 'updatedAt', direction: 'desc' },
    readOnly: false,
    properties: {
      docType: {
        availableValues: [
          { value: 'terms', label: 'terms' },
          { value: 'privacy', label: 'privacy' },
          { value: 'disclaimer', label: 'disclaimer' },
          { value: 'minor-protection', label: 'minor-protection' },
          { value: 'sdk-list', label: 'sdk-list' },
          { value: 'permissions', label: 'permissions' },
          { value: 'account-cancellation', label: 'account-cancellation' },
        ],
      },
    },
  },
};
