import fontkit from '@pdf-lib/fontkit';
import { Injectable } from '@nestjs/common';
import { PDFDocument, rgb } from 'pdf-lib';
import { readFile } from 'node:fs/promises';
import type { ReportDashboardDataDto } from '../../../reports/dto';
import {
  kindLabel,
  statusLabel,
  statusPalette,
} from '../../utils/report-pdf.theme';
import {
  CONTENT_WIDTH,
  MARGIN_X,
  PAGE_HEIGHT,
  PAGE_WIDTH,
  TOP_Y,
} from '../../constants/report-pdf.constants';
import type {
  EmbeddedFont,
  PageContext,
} from '../../constants/report-pdf.constants';
import {
  drawInsightBlock,
  drawMetricsGrid,
  drawPageChrome,
  drawPageDecorations,
  drawScoreCard,
  drawSectionTitle,
  drawSubsectionTitle,
  drawTrendTable,
  drawWrappedText,
  ensureSpace,
} from './draw.service';

const FONT_PATH =
  require.resolve('@fontpkg/source-han-sans-sc-vf/SourceHanSansSC-VF.otf');

type ReportPdfKind = 'hospital' | 'monthly' | 'print';

@Injectable()
export class ReportExportPdfService {
  async buildHospitalPdf(input: {
    locale: string;
    report: ReportDashboardDataDto;
  }): Promise<Buffer> {
    const isZh = input.locale.toLowerCase().startsWith('zh');
    return this.buildPdf(
      'hospital',
      isZh ? 'Lumos 医疗就诊报告' : 'Lumos Hospital Report',
      input.report,
      isZh,
    );
  }

  async buildMonthlyPdf(input: {
    locale: string;
    report: ReportDashboardDataDto;
  }): Promise<Buffer> {
    const isZh = input.locale.toLowerCase().startsWith('zh');
    return this.buildPdf(
      'monthly',
      isZh ? 'Lumos 月度报告' : 'Lumos Monthly Report',
      input.report,
      isZh,
    );
  }

  async buildPrintPdf(input: {
    locale: string;
    report: ReportDashboardDataDto;
  }): Promise<Buffer> {
    const isZh = input.locale.toLowerCase().startsWith('zh');
    return this.buildPdf(
      'print',
      isZh ? 'Lumos 打印报告' : 'Lumos Print Report',
      input.report,
      isZh,
    );
  }

  private async buildPdf(
    kind: ReportPdfKind,
    title: string,
    report: ReportDashboardDataDto,
    isZh: boolean,
  ): Promise<Buffer> {
    const pdf = await PDFDocument.create({ updateMetadata: false });
    pdf.registerFontkit(fontkit);
    const fontBytes = await readFile(FONT_PATH);
    const cjkFont = await pdf.embedFont(fontBytes, { subset: false });
    this.applyMetadata(pdf, title, kind, report, isZh);

    const headerSubtitle = isZh
      ? `统计范围：${report.startDate} ~ ${report.endDate}  ·  生成时间：${report.generatedAt}`
      : `Range: ${report.startDate} ~ ${report.endDate}  ·  Generated at: ${report.generatedAt}`;
    const footerNote = isZh
      ? '说明：本报告用于自我管理与就诊辅助，不替代医生诊断。'
      : 'Note: This report supports self-management and visits, and does not replace medical diagnosis.';
    const pageNumberLabel = isZh
      ? '第 {{page}} / {{total}} 页'
      : 'Page {{page}} / {{total}}';
    const kindLabelText = kindLabel(kind, isZh);
    const context = this.createPageContext({
      pdf,
      cjkFont,
      title,
      headerSubtitle,
      footerNote,
      pageNumberLabel,
      kindLabel: kindLabelText,
    });

    const summaryLabel = isZh ? '概览' : 'Overview';
    const metricsLabel = isZh ? '关键指标' : 'Key Metrics';
    const findingsLabel = isZh ? '发现' : 'Findings';
    const patternsLabel = isZh ? '模式' : 'Patterns';

    ensureSpace(context, 1);
    context.page.drawText(kindLabelText, {
      x: MARGIN_X,
      y: context.cursorY,
      size: 11,
      font: cjkFont,
      color: rgb(0.29, 0.36, 0.46),
    });
    context.cursorY -= 20;

    ensureSpace(context, 1);
    context.page.drawText(
      `${isZh ? '生成时间' : 'Generated at'}: ${report.generatedAt}`,
      {
        x: MARGIN_X,
        y: context.cursorY,
        size: 11,
        font: cjkFont,
        color: rgb(0.35, 0.4, 0.48),
      },
    );
    context.cursorY -= 30;

    drawSectionTitle(context, summaryLabel);
    drawScoreCard(context, report, isZh);
    context.cursorY -= 2;
    drawWrappedText(
      context,
      isZh
        ? '本报告由 Lumos 自动生成，用于就诊时供医生参考，不替代专业诊断。'
        : 'This report is auto-generated by Lumos for doctor reference during visits and does not replace professional diagnosis.',
      9,
      cjkFont,
      CONTENT_WIDTH,
    );
    context.cursorY -= 10;

    drawSectionTitle(context, metricsLabel);
    if (report.metrics.length > 0)
      drawMetricsGrid(context, report.metrics, isZh);
    context.cursorY -= 8;

    const trendsLabel = isZh ? '每日趋势' : 'Daily Trends';
    drawSectionTitle(context, trendsLabel);
    drawTrendTable(context, report.trends, isZh);
    context.cursorY -= 8;

    drawSectionTitle(context, findingsLabel);
    if (report.findings.length === 0) {
      drawWrappedText(
        context,
        isZh
          ? '当前没有额外重点发现。'
          : 'No additional findings for this range.',
        11,
        cjkFont,
        500,
      );
    } else {
      for (const finding of report.findings) {
        drawInsightBlock(context, {
          title: finding.title,
          body: finding.body,
          accentColor: rgb(0.32, 0.45, 0.6),
          backgroundColor: rgb(0.96, 0.98, 1),
        });
      }
    }
    context.cursorY -= 8;

    drawSectionTitle(context, patternsLabel);
    const attentionPatterns = report.patterns.filter(
      (p) => p.status === 'needs_attention',
    );
    const otherPatterns = report.patterns.filter(
      (p) => p.status !== 'needs_attention',
    );
    if (attentionPatterns.length === 0 && otherPatterns.length === 0) {
      drawWrappedText(
        context,
        isZh
          ? '当前没有额外模式信息。'
          : 'No additional patterns for this range.',
        11,
        cjkFont,
        500,
      );
    }
    if (attentionPatterns.length > 0) {
      drawSubsectionTitle(
        context,
        isZh ? '需优先关注' : 'Needs Attention First',
      );
      for (const pattern of attentionPatterns) {
        const palette = statusPalette(pattern.status);
        drawInsightBlock(context, {
          title: pattern.title,
          body: pattern.body,
          accentColor: palette.accent,
          backgroundColor: palette.fill,
          badgeText: statusLabel(pattern.status, isZh),
          badgeColor: palette.text,
          sparkline: pattern.sparkline,
        });
      }
    }
    if (otherPatterns.length > 0) {
      drawSubsectionTitle(context, isZh ? '其余模式' : 'Other Patterns');
      for (const pattern of otherPatterns) {
        const palette = statusPalette(pattern.status);
        drawInsightBlock(context, {
          title: pattern.title,
          body: pattern.body,
          accentColor: palette.accent,
          backgroundColor: palette.fill,
          badgeText: statusLabel(pattern.status, isZh),
          badgeColor: palette.text,
          sparkline: pattern.sparkline,
        });
      }
    }
    drawPageDecorations(context);
    const bytes = await pdf.save();
    return Buffer.from(bytes);
  }

  private applyMetadata(
    pdf: PDFDocument,
    title: string,
    kind: ReportPdfKind,
    report: ReportDashboardDataDto,
    isZh: boolean,
  ): void {
    const kindLabelText = kindLabel(kind, isZh);
    const subject = isZh
      ? `${kindLabelText}，统计范围 ${report.startDate} ~ ${report.endDate}`
      : `${kindLabelText}, range ${report.startDate} ~ ${report.endDate}`;
    const generatedAt = new Date(report.generatedAt);
    pdf.setTitle(title, { showInWindowTitleBar: true });
    pdf.setAuthor('Lumos / Lucent');
    pdf.setSubject(subject);
    pdf.setCreator('Lucent Report Export Service');
    pdf.setProducer('Lucent Report Export Service');
    if (!Number.isNaN(generatedAt.getTime())) {
      pdf.setCreationDate(generatedAt);
      pdf.setModificationDate(generatedAt);
    }
  }

  private createPageContext(input: {
    pdf: PDFDocument;
    cjkFont: EmbeddedFont;
    title: string;
    headerSubtitle: string;
    footerNote: string;
    pageNumberLabel: string;
    kindLabel: string;
  }): PageContext {
    const context: PageContext = {
      ...input,
      page: input.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
      cursorY: TOP_Y,
    };
    drawPageChrome(context);
    return context;
  }
}
