version: 1.0
name: lucent-deploy
displayName: Lucent Deploy
triggers:
  push:
    branches:
      include:
        - main
  manual: {}

variables:
  SERVER_APP_DIR: /opt/lucent/app
  LUCENT_RUNTIME_DIR: /opt/lucent/runtime
  REGISTRY_HOST: ccr.ccs.tencentyun.com
  REGISTRY_NAMESPACE: your-namespace
  REGISTRY_IMAGE_NAME: lucent
  POSTGRES_IMAGE: postgres:18-alpine
  REDIS_IMAGE: redis:8-alpine
  PROMETHEUS_IMAGE: prom/prometheus:v3.12.0
  GRAFANA_IMAGE: grafana/grafana-oss:13.0.2
  NGINX_IMAGE: nginx:1.29.1-alpine

stages:
  - name: build_and_push
    displayName: Build And Push
    jobs:
      build_app:
        steps:
          - checkout
          - build@docker:
              displayName: Build Lucent Image
              registry: ${REGISTRY_HOST}
              namespace: ${REGISTRY_NAMESPACE}
              repository: ${REGISTRY_IMAGE_NAME}
              tags:
                - ${GITEE_COMMIT_SHORT_ID}
                - latest
              dockerfile: ./Dockerfile
  - name: deploy
    displayName: Deploy
    jobs:
      deploy_server:
        steps:
          - shell@agent:
              displayName: Deploy On Server
              script: |
                export SERVER_APP_DIR="${SERVER_APP_DIR}"
                export LUCENT_RUNTIME_DIR="${LUCENT_RUNTIME_DIR}"
                export LUCENT_IMAGE="${GITEE_DOCKER_IMAGE}"
                export POSTGRES_IMAGE="${POSTGRES_IMAGE}"
                export REDIS_IMAGE="${REDIS_IMAGE}"
                export PROMETHEUS_IMAGE="${PROMETHEUS_IMAGE}"
                export GRAFANA_IMAGE="${GRAFANA_IMAGE}"
                export NGINX_IMAGE="${NGINX_IMAGE}"
                sh "${SERVER_APP_DIR}/scripts/deploy/deploy-server-from-image.sh"
