import type { AssistantToolName } from '../../tools/shared/tool-types.js';

// ─── Per-tool keyword matching rules ─────────────────────────────────────────

export const TOOL_KEYWORD_RULES: Record<AssistantToolName, RegExp[]> = {
  get_today_records: [
    /今天/,
    /today/i,
    /今日/,
    /刚刚/,
    /刚才/,
    /今天.*记录/,
    /today.*record/i,
  ],
  get_records_by_date: [
    /昨天/,
    /前天/,
    /\b\d{4}-\d{2}-\d{2}\b/,
    /\d{1,2}月\d{1,2}日/,
    /哪天/,
    /某天/,
    /on\s+\d{4}-\d{2}-\d{2}/i,
  ],
  get_records_by_range: [
    /最近/,
    /近\s*\d+\s*天/,
    /从.*到.*/,
    /between/i,
    /range/i,
    /这周/,
    /上周/,
    /近一周/,
  ],
  get_today_summary_by_date: [
    /今天总结/,
    /当日总结/,
    /那天总结/,
    /某天总结/,
    /today summary/i,
    /today analysis/i,
  ],
  get_report_summary_by_range: [
    /周报/,
    /月报/,
    /报告总结/,
    /报告分析/,
    /7天报告/,
    /30天报告/,
    /last 7 days report/i,
    /last 30 days report/i,
    /report summary/i,
  ],
  get_recent_today_summaries: [
    /今天总结/,
    /today summary/i,
    /历史总结/,
    /之前总结/,
    /历史.*today/i,
    /之前.*today/i,
    /history.*today/i,
    /today ai summary/i,
    /today analysis/i,
  ],
  get_recent_report_summaries: [
    /报告总结/,
    /周报总结/,
    /月报总结/,
    /历史.*报告/,
    /之前.*报告/,
    /历史.*report/i,
    /之前.*report/i,
    /history.*report/i,
    /report ai summary/i,
    /report summary/i,
    /weekly summary/i,
    /monthly summary/i,
  ],
  get_user_profile: [
    /过敏/,
    /allerg/i,
    /病史/,
    /既往/,
    /condition/i,
    /profile/i,
    /血型/,
    /blood type/i,
    /身高/,
    /height/i,
    /年龄/,
    /age/i,
  ],
  get_user_settings: [
    /设置/,
    /权限/,
    /开关/,
    /setting/i,
    /permission/i,
    /toggle/i,
    /enabled/i,
  ],
  get_current_medicines: [
    /药/,
    /用药/,
    /吃药/,
    /服药/,
    /提醒/,
    /medicine/i,
    /medic/i,
    /drug/i,
    /dose/i,
    /dosage/i,
    /pill/i,
    /reminder/i,
  ],
  get_sleep_summary_by_range: [
    /睡眠/,
    /睡得/,
    /失眠/,
    /作息/,
    /sleep/i,
    /rest/i,
    /insomnia/i,
    /近几天睡眠/,
    /最近睡眠/,
  ],
  get_meal_analysis_digest: [
    /饮食/,
    /吃了什么/,
    /吃啥/,
    /吃饭/,
    /餐食/,
    /三餐/,
    /早餐/,
    /午餐/,
    /午饭/,
    /晚餐/,
    /晚饭/,
    /外卖/,
    /热量/,
    /卡路里/,
    /营养/,
    /meal/i,
    /diet/i,
    /calorie/i,
    /nutrition/i,
  ],
  search_cn_medicine_products: [
    /国药准字/,
    /批准文号/,
    /生产厂家/,
    /厂家/,
    /药厂/,
    /商品名/,
    /规格/,
    /胶囊/,
    /片剂?/,
    /颗粒/,
    /口服液/,
    /manufacturer/i,
    /approval number/i,
    /package spec/i,
  ],
  get_cn_medicine_detail: [
    /成分/,
    /厂家/,
    /药厂/,
    /批准文号/,
    /适应症/,
    /规格/,
    /ingredients?/i,
    /manufacturer/i,
    /approval number/i,
    /indication/i,
    /package spec/i,
  ],
  /**
   * 中文散文检索（LightRAG）：既覆盖说明书字段级问题，也覆盖医学问答式问题
   * ——两者在下游由 `source` 参数分流，路由阶段只需要认出"这是在问中文散文知识"。
   * 厂商/批准文号这类**结构化**问题刻意不在这里（它们归
   * `search_cn_medicine_products` 的 SQL 键查）。
   */
  search_cn_medicine_knowledge: [
    /说明书/,
    /成分/,
    /用法用量/,
    /副作用/,
    /不良反应/,
    /禁忌/,
    /注意事项/,
    /药物相互作用/,
    /相互作用/,
    /适应症/,
    /能治什么/,
    /有什么用/,
    /leaflet/i,
    /instruction/i,
    /contraindication/i,
    /precaution/i,
    /side effect/i,
    /dosage/i,
    /drug interaction/i,
    /医学知识/,
    /疾病知识/,
    /病因/,
    /病理/,
    /药理学/,
    /生理学/,
    /临床症状/,
    /预防.*疾病/,
    /什么是.*病/,
    /为什么会.*病/,
    /如何预防/,
    /发病机制/,
    /流行病学/,
    /medical knowledge/i,
    /disease.*knowledge/i,
  ],
  resolve_drugbank_entity: [
    /drugbank/i,
    /药理/,
    /机制/,
    /mechanism/i,
    /相互作用/,
    /interaction/i,
    /药物知识/,
    /scientific/i,
  ],
  get_drugbank_detail: [
    /drugbank/i,
    /机制/,
    /药理/,
    /药代/,
    /药动/,
    /半衰期/,
    /吸收/,
    /代谢/,
    /清除/,
    /分布/,
    /mechanism/i,
    /pharmacokinetic/i,
    /half-life/i,
    /absorption/i,
    /metabolism/i,
    /clearance/i,
    /distribution/i,
    /protein binding/i,
  ],
  search_drugbank_passages: [
    /drugbank/i,
    /药理/,
    /机制/,
    /mechanism/i,
    /相互作用/,
    /interaction/i,
    /药物知识/,
    /scientific/i,
  ],
  reason_over_ontology: [
    // 中文
    /共享靶点/,
    /共同靶点/,
    /同靶点/,
    /靶点/,
    /代谢酶/,
    /同工酶/,
    /能否同服/,
    /同服/,
    /共服/,
    /配伍/,
    /一起吃/,
    /联用/,
    /合用/,
    /抑制.{0,6}酶/,
    /相互作用/,
    // 英文：`/interact/` 覆盖 interact/interacts/interacting/interaction(s)——
    // 只写 `/interaction/` 会漏掉最常见的问法 "Which drugs interact with X?"。
    /interact/i,
    /drug[- ]drug/i,
    /share[sd]? (a |the )?target/i,
    /(same|common|shared) target/i,
    /targets? (of|for)/i,
    /inhibit/i,
    /inhibitor/i,
    /enzyme/i,
    /metaboli[sz]/i,
    /co-?administ/i,
    /take .* together/i,
    /together with/i,
    /combined with/i,
    // 酶/角色类问法：这些问句里没有 "interact" 也没有 "enzyme" 的完整词，
    // 实测（2026-09-19 走 API 的验证）「Which drugs are substrates of CYP3A4?」
    // 与「What ATC class does clopidogrel belong to?」都因此没被提供该工具。
    /substrate/i,
    /cyp\s?\d/i,
    /p450/i,
    /atc/i,
    /belongs? (to|in)/i,
    /class(es)? (is|does|of|are)/i,
  ],
  propose_create_daily_record: [
    /帮我记/,
    /记一下/,
    /记录一下/,
    /添加记录/,
    /新增记录/,
    /save this/i,
    /log this/i,
    /record this/i,
    /add a record/i,
  ],
  propose_update_daily_record: [
    /修改记录/,
    /更新记录/,
    /改一下记录/,
    /记录.*改一下/,
    /记录.*修改/,
    /备注.*改一下/,
    /备注.*修改/,
    /title.*update/i,
    /note.*update/i,
    /edit record/i,
    /update record/i,
    /change record/i,
  ],
  propose_delete_daily_record: [
    /删除记录/,
    /删掉记录/,
    /去掉记录/,
    /记录.*删除/,
    /记录.*删掉/,
    /delete record/i,
    /remove record/i,
  ],
  propose_update_user_settings: [
    /打开.*ai/,
    /关闭.*ai/,
    /关掉.*ai/,
    /打开.*记忆/,
    /关闭.*记忆/,
    /关掉.*记忆/,
    /打开.*权限/,
    /关闭.*权限/,
    /关掉.*权限/,
    /assistant memory/i,
    /turn on/i,
    /turn off/i,
    /enable/i,
    /disable/i,
  ],
};

// ─── Broad fallback rules ────────────────────────────────────────────────────

export const BROAD_RECORD_QUERY_RULES = [
  /记录/,
  /record/i,
  /日志/,
  /饮水/,
  /喝水/,
  /water/i,
  /meal/i,
  /吃饭/,
  /symptom/i,
  /症状/,
  /note/i,
] as const;

export const BROAD_PERSONALIZED_QUERY_RULES = [
  /最近/,
  /这几天/,
  /lately/i,
  /recently/i,
  /overview/i,
  /summary/i,
  /情况/,
  /状态/,
  /怎么办/,
  /what should i do/i,
  /how am i/i,
] as const;

export const WRITE_INTENT_RULES = [
  /帮我记/,
  /记一下/,
  /记录一下/,
  /添加/,
  /新增/,
  /修改/,
  /更新/,
  /删除/,
  /删掉/,
  /关掉/,
  /save/i,
  /log/i,
  /record/i,
  /update/i,
  /delete/i,
  /remove/i,
  /turn on/i,
  /turn off/i,
  /enable/i,
  /disable/i,
] as const;

export const EXPLICIT_CN_PRODUCT_RULES = [
  /国药准字/,
  /批准文号/,
  /生产厂家/,
  /厂家/,
  /药厂/,
  /商品名/,
  /规格/,
  /胶囊/,
  /片剂?/,
  /颗粒/,
  /口服液/,
] as const;

export const CN_LEAFLET_STYLE_RULES = [
  /说明书/,
  /成分/,
  /适应症/,
  /禁忌/,
  /注意事项/,
  /不良反应/,
  /副作用/,
  /药物相互作用/,
  /相互作用/,
] as const;
